### ISSUE TITLE
Silkscreen issues on board v0.5

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [elektronomikon/raspi_gpib_shield#2]
The silkscreen of board v0.5 could be improved:

* The component numbers of the resistor networks are positioned in places where holes overlap (marked in red). It's hard to figure out which one is which.
* The ICs should have an indicator for the placement (marked in red)
* The GPIO header is supposed to be placed from the bottom, so its silk screen should be on the bottom, too (marked blue)
* IMHO, the mounting holes do not necessarily need a silk screen. But if they have, I'd prefer a readable silk screen for all of them, not only MK4.
* Resistors R3 .. R18 might have the label inside the component instead of overlapping with the next resistor

![grafik](https://user-images.githubusercontent.com/25632350/93754577-44a4b300-fc02-11ea-9540-e385e3247dcd.png)

From the photo for v0.4, it seems the silk screen was better.

**Comment by elektronomikon** [comment]
Hi,

i absolutely agree, all labels and values are now readable in V.6 - just a mounting hole label snuck in ;-)

Thanks for the hint w.r.t the nose on U1 and U2, totally missed those.

If you want to take a look at V.6, it looks like this:
[https://github.com/elektronomikon/raspi_gpib_shield/raw/master/Documentation/Raspi_GPIB_V6%20PCB%20render.png](https://github.com/elektronomikon/raspi_gpib_shield/raw/master/Documentation/Raspi_GPIB_V6%20PCB%20render.png)

In closing, the next version should probably feature:
-) A RasPi Port label which is not riddled with holes from vias
-) Sane numbers on the resistor labels
-) RN1/2 or RN3/4 swapped for symmetry
-) PWR/ACT instead of LED1/2
-) No MK1 label
-) Directional indicators on U1/2

Thank you very much for your time!

have fun,
Thomas

**Comment by thomasw-mitutoyo-ctl** [comment]
Thanks, v0.6 looks great.
